services:
  mongo:
    image: mongo:8.0.4
    container_name: mongo-database
    ports:
      - "27017:27017"
    volumes:
      - .mongo-data:/data/db
  redis:
    build: .
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - .redis-data:/data
