services:
  mongo:
    image: mongo:8.0.4
    container_name: mongo-database
    ports:
      - "27017:27017"
    volumes:
      - .mongo-data:/data/db
  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
